-- Allow multiple variants per slot on customer_signals + industry_intel.
--
-- The variant store (20260507150000) added variant_id / win_count /
-- loss_count to all four cabinet tables, but the original unique
-- constraints from 20260507130000 only allow ONE row per slot:
--
--   customer_signals  UNIQUE (dealership_id, signal_key)
--   industry_intel    UNIQUE (dealership_id, scope, topic)
--
-- That blocks the bandit — you can't have two competing
-- response_variant rows for signal_key='too_low' to A/B test.
-- conversation_phases already has variant_label and a 3-column
-- unique constraint, so it's fine; voice_agent_persona is a
-- single-arm slot by design (one persona per name).
--
-- This migration brings signals + intel up to the phases pattern:
--   - Add variant_label text default 'default'
--   - Drop the old 2-col / 3-col unique
--   - Add a new unique that includes variant_label
--
-- Existing rows back-fill to variant_label = 'default' so the unique
-- constraint stays valid through the change.
--
-- Idempotent.

-- ── customer_signals ──────────────────────────────────────────────
ALTER TABLE public.customer_signals
  ADD COLUMN IF NOT EXISTS variant_label text NOT NULL DEFAULT 'default';

-- Drop the old unique if still present (named auto-generated by PG).
DO $$
DECLARE
  _conname text;
BEGIN
  SELECT conname INTO _conname
  FROM pg_constraint
  WHERE conrelid = 'public.customer_signals'::regclass
    AND contype = 'u'
    AND pg_get_constraintdef(oid) LIKE '%(dealership_id, signal_key)%'
    AND pg_get_constraintdef(oid) NOT LIKE '%variant_label%';
  IF _conname IS NOT NULL THEN
    EXECUTE format('ALTER TABLE public.customer_signals DROP CONSTRAINT %I', _conname);
  END IF;
END $$;

-- Add the new variant-aware unique if it isn't already there.
DO $$
BEGIN
  IF NOT EXISTS (
    SELECT 1 FROM pg_constraint
    WHERE conrelid = 'public.customer_signals'::regclass
      AND contype = 'u'
      AND pg_get_constraintdef(oid) LIKE '%(dealership_id, signal_key, variant_label)%'
  ) THEN
    ALTER TABLE public.customer_signals
      ADD CONSTRAINT customer_signals_dealer_key_variant_unique
      UNIQUE (dealership_id, signal_key, variant_label);
  END IF;
END $$;

-- ── industry_intel ────────────────────────────────────────────────
ALTER TABLE public.industry_intel
  ADD COLUMN IF NOT EXISTS variant_label text NOT NULL DEFAULT 'default';

DO $$
DECLARE
  _conname text;
BEGIN
  SELECT conname INTO _conname
  FROM pg_constraint
  WHERE conrelid = 'public.industry_intel'::regclass
    AND contype = 'u'
    AND pg_get_constraintdef(oid) LIKE '%(dealership_id, scope, topic)%'
    AND pg_get_constraintdef(oid) NOT LIKE '%variant_label%';
  IF _conname IS NOT NULL THEN
    EXECUTE format('ALTER TABLE public.industry_intel DROP CONSTRAINT %I', _conname);
  END IF;
END $$;

DO $$
BEGIN
  IF NOT EXISTS (
    SELECT 1 FROM pg_constraint
    WHERE conrelid = 'public.industry_intel'::regclass
      AND contype = 'u'
      AND pg_get_constraintdef(oid) LIKE '%(dealership_id, scope, topic, variant_label)%'
  ) THEN
    ALTER TABLE public.industry_intel
      ADD CONSTRAINT industry_intel_dealer_topic_variant_unique
      UNIQUE (dealership_id, scope, topic, variant_label);
  END IF;
END $$;

NOTIFY pgrst, 'reload schema';
